AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Core Ocean Iceberg Utils Layer

Resources:
  Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: core-ocean-iceberg-utils
      Description: Utilities and dependencies for core-iceberg
      ContentUri: ../../target/core-iceberg-utils.zip
      LicenseInfo: MIT
      CompatibleRuntimes:
        - java17
    Metadata:
      BuildMethod: java17
      BuildArchitecture: x86_64

Outputs:
  Arn:
    Value: !Ref Layer
