AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Core Ocean Iceberg Utils Layer Role

Parameters:
  RoleName:
    Description: Name of the IAM Role for the deployment
    Type: String
    Default: "GitHubDeployCoreOceanIcebergUtils"

Resources:
  Role:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-2:${AWS::AccountId}:applications/core-aws-github-role
        SemanticVersion: 0.0.3
      Parameters:
        GitHubOrg: tiki
        RepositoryName: core-ocean-iceberg-utils
        RoleName: !Ref RoleName

  Policy:
    Type: AWS::IAM::RolePolicy
    DependsOn: Role
    Properties:
      RoleName: !Ref RoleName
      PolicyName: DeploymentPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: cloudformation:*
            Resource:
              - !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/core-iceberg-utils-layer/*
              - arn:aws:cloudformation:us-east-2:aws:transform/Serverless-2016-10-31
          - Effect: Allow
            Action: cloudformation:ListStacks
            Resource: "*"
          - Effect: Allow
            Action: iam:PassRole
            Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/${RoleName}
            Condition:
              StringEquals:
                iam:PassedToService: lambda.amazonaws.com
          - Effect: Allow
            Action:
              - lambda:ListLayers
              - lambda:ListLayerVersions
            Resource: "*"
          - Effect: Allow
            Action:
              - lambda:GetLayerVersion
              - lambda:GetLayerVersionPolicy
              - lambda:AddLayerVersionPermission
              - lambda:RemoveLayerVersionPermission
            Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:core-iceberg-utils:*
          - Effect: Allow
            Action: lambda:PublishLayerVersion
            Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:core-iceberg-utils
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
            Resource: !Sub arn:aws:s3:::mytiki-sam-deploy/*
