AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Core Iceberg Utility Role

Parameters:
  RoleName:
    Description: Name of the IAM Role for the deployment
    Type: String
    Default: "GitHubDeployCoreIcebergUtils"

Resources:
  Role:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-2:${AWS::AccountId}:applications/core-aws-github-role
        SemanticVersion: 0.0.2
      Parameters:
        GitHubOrg: tiki
        RepositoryName: core-iceberg-utils
        RoleName: !Ref RoleName

  Policy:
    Type: AWS::IAM::RolePolicy
    Properties:
      RoleName: !Ref RoleName
      PolicyName: DeploymentPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - iam:CreateRole
              - iam:TagRole
              - iam:GetRolePolicy
              - iam:PutRolePolicy
              - iam:AttachRolePolicy
              - iam:GetRole
            Resource: "*"
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource: "*"
            Condition:
              StringEquals:
                iam:PassedToService: lambda.amazonaws.com
          - Effect: Allow
            Action:
              - lambda:GetLayerVersion
              - lambda:GetLayerVersionPolicy
              - lambda:ListLayers
              - lambda:ListLayerVersions
              - lambda:DeleteLayerVersion
              - lambda:PublishLayerVersion
              - lambda:AddLayerVersionPermission
              - lambda:RemoveLayerVersionPermission
            Resource: "*"
